# Site settings
title: Andrew J Skelton
email: andrew.j.skelton73@gmail.com
url: https://andrewskelton.github.io
description: "Portfolio of Andrew J Skelton | Newcastle Upon Tyne | Bioinformatics | Machine Learning | Biostatistics | NGS | Sequencing | Clinical | Statistics |"
skills: "Data Science | Bioinformatics | Machine Learning | Statistics"
meta_author: Skelton Andrew J

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1267a2 #
  primary-rgb: "18,103,162"  #"128,179,255" #"24,288,156"
  secondary: 2c3e50 #2c3e50 #This is the Banner Colour
  secondary-dark: 233140 #

# Footer settings
footer:
  copyright: Andrew Skelton
  location: Newcastle Upon Tyne
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ajskelton73
  - title: flask
    url: https://www.biostars.org/u/9912/
  - title: github
    url: https://github.com/AndrewSkelton

# Postal address (add as many lines as necessary)
address:
  - line: Newcastle Upon Tyne
  - line: United Kingdom

# Credits content
credits: 'AJS'

# Build settings
markdown: kramdown
permalink: pretty
